### ISSUE TITLE
Ambiguity in Oasis2

### ISSUE THREAD

**Issue by ChucklesTheBeard** [Fartlicker777/Cruel-Garfield-Kart#2]
The driver's rank only goes from 2 to 1... the mode is 1, 2, the median is 1.5. Is this meant to be rounded down to 1?

**Comment by Fartlicker777** [comment]
Whenever a non-integer median is not possible, you have to take the mode

**Comment by ChucklesTheBeard** [comment]
2 occurs once, and 1 occurs once. "Mode" is defined as "the most frequent value of a set of data". What is the most frequent value in a list of length two?

**Comment by ChucklesTheBeard** [comment]
Actually, manual's been updated to show "Take the median and round down" so the point is moot.
